export const resturentDetails = [
  {
    id: 1,
    name: "Spicy Tadka",
    rating: 4.5,
    cuisine: "Indian",
    dish: "Pani Puri",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/7-pani-puri-canva-phpxM6qmK",
    imageId: "7-pani-puri-canva-phpxM6qmK",
    address: "12, Indiranagar, Bangalore, India",
  },
  {
    id: 2,
    name: "Chef's Table",
    rating: 2.8,
    cuisine: "Continental",
    dish: "Gourmet Salad",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/ChefKatie-561-phpDEMb5I",
    imageId: "ChefKatie-561-phpDEMb5I",
    address: "22, Koramangala, Bangalore, India",
  },
  {
    id: 3,
    name: "Royal Naan House",
    rating: 4.6,
    cuisine: "North Indian",
    dish: "Butter Naan",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/1-naan-canva-phpj3pPkG",
    imageId: "1-naan-canva-phpj3pPkG",
    address: "33, Jayanagar, Bangalore, India",
  },
  {
    id: 4,
    name: "Samosa Junction",
    rating: 4.3,
    cuisine: "Snacks",
    dish: "Samosa Platter",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/5-samosas-canva-phppf0Q4I",
    imageId: "5-samosas-canva-phppf0Q4I",
    address: "55, HSR Layout, Bangalore, India",
  },
  {
    id: 5,
    name: "Kachori Khaas",
    rating: 4.4,
    cuisine: "Indian",
    dish: "Kachori with Chutney",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/9-kachori-canva-phpUP6psD",
    imageId: "9-kachori-canva-phpUP6psD",
    address: "14, Whitefield, Bangalore, India",
  },
  {
    id: 6,
    name: "Kulcha Kitchen",
    rating: 4.2,
    cuisine: "Punjabi",
    dish: "Matar Kulcha",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/11-matar-kulcha-canva-phpiqTrzB",
    imageId: "11-matar-kulcha-canva-phpiqTrzB",
    address: "78, MG Road, Bangalore, India",
  },
  {
    id: 7,
    name: "Vada Pav House",
    rating: 3.7,
    cuisine: "Maharashtrian",
    dish: "Vada Pav",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/13-vada-pav-canva-phpFSOPxs",
    imageId: "13-vada-pav-canva-phpFSOPxs",
    address: "24, Indiranagar, Bangalore, India",
  },
  {
    id: 8,
    name: "Roll It Up",
    rating: 4.5,
    cuisine: "Street Food",
    dish: "Kathi Rolls",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/15-kathi-rolls-canva-phpE9mepi",
    imageId: "15-kathi-rolls-canva-phpE9mepi",
    address: "19, JP Nagar, Bangalore, India",
  },
  {
    id: 9,
    name: "Pakora Junction",
    rating: 4.3,
    cuisine: "Snacks",
    dish: "Assorted Pakoras",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/17-pakora-canva-phpCKAtC4",
    imageId: "17-pakora-canva-phpCKAtC4",
    address: "20, Bannerghatta Road, Bangalore, India",
  },
  {
    id: 10,
    name: "Chicken Delight",
    rating: 4.6,
    cuisine: "Indian",
    dish: "Chicken 65",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/19-chicken-65-canva-phpV0OB8z",
    imageId: "19-chicken-65-canva-phpV0OB8z",
    address: "88, Brigade Road, Bangalore, India",
  },
  {
    id: 11,
    name: "Dosa Corner",
    rating: 4.5,
    cuisine: "South Indian",
    dish: "Sambar Dosa",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/21-sambar-canva-php6n3V6O",
    imageId: "21-sambar-canva-php6n3V6O",
    address: "41, Koramangala, Bangalore, India",
  },
  {
    id: 12,
    name: "Coconut Curries",
    rating: 3.8,
    cuisine: "Seafood",
    dish: "Fish Curry",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/22ish-fish-seafood-curries-coconut-milk-canva-phpse0Ty3",
    imageId: "22ish-fish-seafood-curries-coconut-milk-canva-phpse0Ty3",
    address: "100, Indiranagar, Bangalore, India",
  },
  {
    id: 13,
    name: "Tandoor Flames",
    rating: 4.7,
    cuisine: "Indian",
    dish: "Tandoori Chicken",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/23-tandoor-canva-phpRi8NmQ",
    imageId: "23-tandoor-canva-phpRi8NmQ",
    address: "10, Whitefield, Bangalore, India",
  },
  {
    id: 14,
    name: "Butter Bowl",
    rating: 3.6,
    cuisine: "North Indian",
    dish: "Butter Chicken",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/25-butter-chicken-murgh-makhani-canva-phpcxhfCA",
    imageId: "25-butter-chicken-murgh-makhani-canva-phpcxhfCA",
    address: "23, MG Road, Bangalore, India",
  },
  {
    id: 15,
    name: "Kofta Kitchen",
    rating: 2.5,
    cuisine: "Indian",
    dish: "Malai Kofta",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/27-malai-kofta-canva-php4HbTC1",
    imageId: "27-malai-kofta-canva-php4HbTC1",
    address: "80, Jayanagar, Bangalore, India",
  },
  {
    id: 16,
    name: "Rogan Rolls",
    rating: 2.4,
    cuisine: "North Indian",
    dish: "Rogan Josh",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/29-rogan-josh-canva-php0oPsU8",
    imageId: "29-rogan-josh-canva-php0oPsU8",
    address: "44, Sarjapur Road, Bangalore, India",
  },
  {
    id: 17,
    name: "Saag Sensation",
    rating: 4.3,
    cuisine: "North Indian",
    dish: "Palak Paneer",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/31-saag-canva-phpJ2CE1n",
    imageId: "31-saag-canva-phpJ2CE1n",
    address: "99, BTM Layout, Bangalore, India",
  },
  {
    id: 18,
    name: "Masala Magic",
    rating: 4.6,
    cuisine: "Indian",
    dish: "Chana Masala",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/33-chana-masala-canva-phphQcG8p",
    imageId: "33-chana-masala-canva-phphQcG8p",
    address: "11, Rajajinagar, Bangalore, India",
  },
  {
    id: 19,
    name: "Biryani Bliss",
    rating: 3.9,
    cuisine: "Indian",
    dish: "Hyderabadi Biryani",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/35-biryani-canva-phpxov0UZ",
    imageId: "35-biryani-canva-phpxov0UZ",
    address: "70, Hebbal, Bangalore, India",
  },
  {
    id: 20,
    name: "Thali Tales",
    rating: 4.7,
    cuisine: "Indian",
    dish: "Veg Thali",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/37-thali-canva-phpAAsz1i",
    imageId: "37-thali-canva-phpAAsz1i",
    address: "40, Electronics City, Bangalore, India",
  },
  {
    id: 21,
    name: "Kulfi Kraze",
    rating: 4.5,
    cuisine: "Desserts",
    dish: "Malai Kulfi",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/39-kulfi-canva-phposOcGE",
    imageId: "39-kulfi-canva-phposOcGE",
    address: "35, Yelahanka, Bangalore, India",
  },
  {
    id: 22,
    name: "Sweet Tooth",
    rating: 4.3,
    cuisine: "Desserts",
    dish: "Gulab Jamun",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/41-gulab-jamun-canva-phpmGfh29",
    imageId: "41-gulab-jamun-canva-phpmGfh29",
    address: "15, Kormangala, Bangalore, India",
  },
  {
    id: 23,
    name: "Milk Barfi",
    rating: 3.2,
    cuisine: "Desserts",
    dish: "Milk Barfi",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/43-barfi-canva-php71vYPq",
    imageId: "43-barfi-canva-php71vYPq",
    address: "12, Frazer Town, Bangalore, India",
  },
  {
    id: 24,
    name: "Lassi Corner",
    rating: 2.2,
    cuisine: "Drinks",
    dish: "Mango Lassi",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/45-lassi-canva-phpOntkP2",
    imageId: "45-lassi-canva-phpOntkP2",
    address: "22, Yeshwanthpur, Bangalore, India",
  },
  {
    id: 25,
    name: "Bangalore Bites",
    rating: 3.0,
    cuisine: "Multi-cuisine",
    dish: "Paneer Tikka",
    photo:
      "https://res.cloudinary.com/hz3gmuqw6/image/upload/c_fill,q_60,w_750,f_auto/15-kathi-rolls-canva-phpE9mepi",
    imageId: "15-kathi-rolls-canva-phpE9mepi",
    address: "14, MG Road, Bangalore, India",
  },
];
